---
- name: monitoring_slice1
  command: /root/Automation/monitor_SLICE1.sh execute '"bin","start"' 'SIMULATION' 'simulation/simulations/N2_SLICE1'

- name: Wait
  wait_for:
    delay: 60
    timeout: 0

- name: get long stats
  command: /root/Automation/monitor_SLICE1.sh statl Data

- name: get short stats
  command: /root/Automation/monitor_SLICE1.sh stats Data
